# Generated by Django 4.1.3 on 2023-04-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Url', models.CharField(max_length=30)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
    ]
